pipeline {
    agent any
	
	tools {
		maven 'Maven'
		}
	
    stages{
        stage('Code-Compile'){
            steps{
                // checkout ansible tasks
                echo "Code Compile Started"
				git 'https://github.com/vgvivekgupt/samplejavaapp.git'
				sh '/opt/maven/bin/mvn compile'
				echo "Code Compile Done"
				
            }
        }
        stage('Code-Review'){           
            steps{
                // checkout ansible tasks
				echo "Code Review started"
				git 'https://github.com/vgvivekgupt/samplejavaapp.git'
				sh '/opt/maven/bin/mvn -P metrics pmd:pmd'
				echo "Code Review Done"
				}
		post {
			success {
				recordIssues sourceCodeRetention: 'LAST_BUILD', tools: [pmdParser(pattern: '**/pmd.xml')]
			}
				}
			}        
    stage('Code-Test'){
        steps{
            echo "Code Testing Started"
			git 'https://github.com/vgvivekgupt/samplejavaapp.git'
			sh '/opt/maven/bin/mvn test'
			echo "Code Testing Done"
        }
		post {
			success {
				junit stdioRetention: '', testResults: 'target/surefire-reports/*.xml'
				}
}
    }
    stage('Code-Coverage'){
        steps{
            echo "Code Coverage started"
			git 'https://github.com/vgvivekgupt/samplejavaapp.git'
			sh '/opt/maven/bin/mvn verify'
			echo "Code Coverage Done"
			
        }
		post {
			success {
				jacoco maximumBranchCoverage: '2'
				}
			}
	}
    stage('Code-Build'){
        steps{
            echo "Code Build started"
			git 'https://github.com/vgvivekgupt/samplejavaapp.git'
			sh '/opt/maven/bin/mvn package'
			echo "Code Build Done"
        }
		post {
			success {
				archiveArtifacts artifacts: 'target/*.war', followSymlinks: false
				}
    }
	}
	}
    post{
     always{
        echo "notifier"
        }
    }	
}	
